### ISSUE TITLE
circleci builds failing, possibly outdated credentials

### ISSUE THREAD

**Issue by ericmanlol** [weaveworks/prom-aggregation-gateway#13]
It looks like the builds have been failing for over a year now on circleci in the deployment step because it can push to quay but it can't properly login and finish the push to the docker hub here: https://github.com/weaveworks/prom-aggregation-gateway/blob/master/circle.yml#L29

Please update the credentials in the circleci job so the builds pass

**Comment by bboreham** [comment]
I believe CircleCI is working now for this repo.
