### ISSUE TITLE
[question] can't build

### ISSUE THREAD

**Issue by karolzmijewski** [weaveworks/prom-aggregation-gateway#16]
Hi guys, what I'm doing wrong?

make all
docker build -t quay.io/weaveworks/aggate-build aggate-build/
Sending build context to Docker daemon 3.584 kB
Step 1/3 : FROM quay.io/weaveworks/build-golang:master-7fab441
Trying to pull repository quay.io/weaveworks/build-golang ... 
unexpected http code: 400, URL: https://quay.io/v2/auth?scope=repository%3Aweaveworks%2Fbuild-golang%3Apull&service=quay.io
make: *** [Makefile:15: aggate-build/.uptodate] Error 1

**Comment by karolzmijewski** [comment]
I'm not sure if anyone will look at it, but it seems that it is something wrong with: **quay.io/weaveworks/build-golang** reqistry. Makefile is trying to make docker pull on it, and it can't:

```
level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration"
level=debug msg=" Using \"default-docker\" configuration"
level=debug msg=" No signature storage configuration found for quay.io/weaveworks/build-golang:latest"
level=debug msg="GET https://quay.io/v2/"
level=debug msg="Ping https://quay.io/v2/ err <nil>"
level=debug msg="Ping https://quay.io/v2/ status 401"
level=error msg="Error trying v2 registry: unexpected http code: 400, URL: https://quay.io/v2/auth?scope=repository%3Aweaveworks%2Fbuild-golang%3Apull&service=quay.io"
level=error msg="Attempting next endpoint for pull after error: unexpected http code: 400, URL: https://quay.io/v2/auth?scope=repository%3Aweaveworks%2Fbuild-golang%3Apull&service=quay.io"
level=debug msg="Skipping v1 endpoint https://quay.io because v2 registry was detected"
level=debug msg="AuthZ response using plugin rhel-push-plugin"
```

You may check this namespace manually, it returns:
`{"errors":[{"code":"NAMESPACE_DISABLED","detail":{},"message":"Namespace weaveworks has been disabled. Please contact a system administrator."}]}`

**Comment by karolzmijewski** [comment]
Same error when I'm trying to pull build with exec inside:
`docker pull quay.io/weaveworks/prom-aggregation-gateway:latest`

**Comment by bboreham** [comment]
Yes, quay.io have disabled that namespace.
You should be able to use the same-named images from Dockerhub, i.e. remove `quay.io` from the name.
#15 is work in progress to fix the CI build, including this issue.

**Comment by tamsky** [comment]
If #15 has been merged, this should mean
- everyone should now be able to run `make all`
- this issue can be closed
?

**Comment by bboreham** [comment]
I'll close for now - please reopen and give details if you still have an issue.
