### ISSUE TITLE
Question: how to communicate securely with the gateway

### ISSUE THREAD

**Issue by caiobegotti** [weaveworks/prom-aggregation-gateway#24]
Sorry but I can't ask that via Slack so I hope this is fine to be raised here: how we could securely communicate with the gateway from the client side in order to prevent people from sending bogus or intentionally wrong/bad data to the gateway using promjs or something else since it's all client-side?

**Comment by bboreham** [comment]
If you have a way to get credentials securely to your clients then you can put prom-aggregation-gateway behind a reverse-proxy that authenticates those credentials.
