### ISSUE TITLE
Histogram aggregation (runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by aosavitski** [weaveworks/prom-aggregation-gateway#51]
Hi,

If I am pushing histogram metrics with only le property then everything works fine.
Example:
`curl -d $'# TYPE test_v1 histogram\ntest_v1_bucket{le="25"} 0\ntest_v1_bucket{le="50"} 2\ntest_v1_bucket{le="80"} 2\ntest_v1_bucket{le="100"} 3\ntest_v1_bucket{le="150"} 3\ntest_v1_bucket{le="200"} 3\ntest_v1_bucket{le="250"} 3\ntest_v1_bucket{le="300"} 3\ntest_v1_bucket{le="400"} 3\ntest_v1_bucket{le="500"} 3\ntest_v1_bucket{le="800"} 3\ntest_v1_bucket{le="+Inf"} 3\ntest_v1_count 3\ntest_v1_sum 152.2200000108569\n' http://localhost/metrics/`

I can execute this several time and all the bucket numbers will be aggregated. 

But if together with le I have some custom properties in my metrics, then 1st time data will be pushed, but 2nd call will raise an error:
`curl -d $'# TYPE test_v2 histogram\ntest_v2_bucket{le="25",instance="a"} 0\ntest_v2_bucket{le="50",instance="a"} 2\ntest_v2_bucket{le="80",instance="a"} 2\ntest_v2_bucket{le="100",instance="a"} 3\ntest_v2_bucket{le="150",instance="a"} 3\ntest_v2_bucket{le="200",instance="a"} 3\ntest_v2_bucket{le="250",instance="a"} 3\ntest_v2_bucket{le="300",instance="a"} 3\ntest_v2_bucket{le="400",instance="a"} 3\ntest_v2_bucket{le="500",instance="a"} 3\ntest_v2_bucket{le="800",instance="a"} 3\ntest_v2_bucket{le="+Inf",instance="a"} 3\ntest_v2_count 3\ntest_v2_sum 152.2200000108569\n' http://localhost/metrics/`

`2021/01/21 19:25:49 http: panic serving 172.17.0.1:41728: runtime error: invalid memory address or nil pointer dereference
goroutine 53 [running]:
net/http.(*conn).serve.func1(0xc0001a4780)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x6e8760, 0x9b96d0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
main.mergeMetric(0xc000000004, 0xc0000a7aa0, 0xc0001ee060, 0xc00000e0d0)
        /go/src/github.com/weaveworks/prom-aggregation-gateway/cmd/prom-aggregation-gateway/main.go:106 +0x2d6
main.mergeFamily(0xc0000e46e0, 0xc0000e47d0, 0xc00001bbb8, 0x7, 0xc0001be160)
        /go/src/github.com/weaveworks/prom-aggregation-gateway/cmd/prom-aggregation-gateway/main.go:149 +0x431
main.(*aggate).parseAndMerge(0xc0000d0320, 0x7f286b4ff008, 0xc0000a2d40, 0x0, 0x0)
        /go/src/github.com/weaveworks/prom-aggregation-gateway/cmd/prom-aggregation-gateway/main.go:227 +0x2e0
main.main.func1(0x7b09e0, 0xc0001b8b60, 0xc0001b1000)
        /go/src/github.com/weaveworks/prom-aggregation-gateway/cmd/prom-aggregation-gateway/main.go:271 +0x186
net/http.HandlerFunc.ServeHTTP(0xc0000d0340, 0x7b09e0, 0xc0001b8b60, 0xc0001b1000)
        /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x9c5cc0, 0x7b09e0, 0xc0001b8b60, 0xc0001b1000)
        /usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000d2d00, 0x7b09e0, 0xc0001b8b60, 0xc0001b1000)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0001a4780, 0x7b1420, 0xc0000a2cc0)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
`

**Comment by IMBlues** [comment]
I encountered a similar problem, and I found that the main problem is that the format of metrics will cause an exception in the metric parsing.

the format that caused the exception：

```
# TYPE test_v2 histogram\ntest_v2_bucket{le="25",instance="a"} 0
test_v2_bucket{le="50",instance="a"} 2
test_v2_bucket{le="80",instance="a"} 2
test_v2_bucket{le="100",instance="a"} 3
test_v2_bucket{le="150",instance="a"} 3
...
test_v2_bucket{le="+Inf",instance="a"} 3
test_v2_count 3
test_v2_sum 152.2200000108569
```

fixed ：
```
# TYPE test_v2 histogram\ntest_v2_bucket{le="25",instance="a"} 0
test_v2_bucket{le="50",instance="a"} 2
test_v2_bucket{le="80",instance="a"} 2
test_v2_bucket{le="100",instance="a"} 3
test_v2_bucket{le="150",instance="a"} 3
...
test_v2_bucket{le="+Inf",instance="a"} 3
test_v2_count{instance="a"} 3
test_v2_sum{instance="a"} 152.2200000108569
```
